### ISSUE TITLE
k!event features

### ISSUE THREAD

**Issue by Night-Sin** [SkyKings-Guild/SkyKings#5]
## The Bug

When we create an event in a server, there are multiple issues, it cannot go past 1 day, when ending an event, it says there isn't an event active, but when creating another event, it says there's an event active.  

Edit: ok, 2 of three of the issues were resolved, but I think it should be made clear that when running k!event end before the leaderboard is created, it can't end the event.
## Reproduction Steps
1st issue. Run k!event start (all inputs) and when entering 7d, it doesn't register it as a duration. 

## Expected behavior

1st issue. I expected to be able to run an event past 1 day

**Comment by plun1331** [comment]
Second and third issues have been fixed, I cannot reproduce the first.

**Comment by M4aXim** [comment]
you have to do after event do K!event delete
